apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment-6479
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      serviceAccountName: webapp-sa-6479
      containers:
      - name: webapp
        image: anandkumarmk6479/pyweb:v1
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: webapp-config
        - secretRef:
            name: webapp-secret-6479
        volumeMounts:
        - name: data
          mountPath: /data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: webapp-pvc-6479

